#services:
#  db:
#    image: postgres
#    restart: always
#    container_name: db
#    environment:
#      -POSTGRES_USER=project
#      -POSTGRES_PASSWORD=root
#      -POSTGRES_DB=postgres
#    volumes:
#      - pg_postgres:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#      -
#  app:
#    build: .
#    restart: always
#    container_name: app
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/postgres'
#      JAVA_OPTS: '-Xmx512m'


version: '3.8'
services:
  app:
    image: openjdk:11-jre-slim
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: project
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: [ "java", "-jar", "/app/project.jar" ]
  db:
    image:
      postgres:13
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: project
      POSTGRES_PASSWORD: root
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

volumes:
  postgres_data:
